# -*- coding: utf-8 -*-
"""Лаба 1, Замковой

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1quFR6ZJCBEKSvJvsQhYiH14yU5n4CPg8
"""

# задагие 1
a=5
b=int(input('Введите число '))
s=a*b
print(s)

# задание 2
a=int(input('Введите число '))
b=int(input('Введите число '))
s=(a+b)**2
print(s)

# задание3
a=15
b=10
c=int(input('Введите число '))
s=(a+b)/c
print(s)

# задание 4
a=int(input('Введите число '))
b=int(input('Введите число '))
s=(a+b)**2
print(s)

# задание 5
a=int(input('Введите число '))
b=int(input('Введите число '))
c=int(input('Введите число '))
P=a+b+c
p=P//2
s=(p*(p-a)*(p-b)*(p-c))**0.5
print(P,s)

# задание 6
a=int(input('Введите число '))
b=int(input('Введите число '))
s=(((a)**3+14)//5)*b
print(s)

# задание 7
a=int(input('Введите число '))
n=int(input('Введите число '))
s=(a**2)//n
print(s)

# задание 8
a=float(input('Введите число '))
n=float(input('Введите число '))
s=a//n
print(s)
b=int(input('Введите число '))
c=int(input('Введите число '))
i=b*c
print(i)
l=int(input('Введите число '))
m=int(input('Введите число '))
p=l%m
print(p)




# задания повышенной сложности
# задание 1
n=int(input('Введите число секунд '))
day=n//86400
chasi=n%86400//3600
minyti=n%86400%3600//60
print("day", day)
print("chasi", chasi)
print("minyti", minyti)

# задание 2
n=int(input('Введите число '))
j=n+n**2+n**3
print(j)