# -*- coding: utf-8 -*-
"""Лаб 3, Замковой

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13OxVDDRzGMPmOURkN_t-8e29KWrcGjil
"""

# задача 1
n=int(input('Введите номер месяца '))
if n==1:
   print('январь')
if n==2:
   print('февраль')
if n==3:
   print('март')
if n==4:
   print('апрель')
if n==5:
   print('май')
if n==6:
   print('июнь')
if n==7:
   print('июль')
if n==8:
   print('август')
if n==9:
   print('сентябрь')
if n==10:
   print('октябрь')
if n==11:
   print('ноябрь')
if n==12:
   print('декабрь')

# задание 2
n=int(input('Введите число '))
if n%2==1:
   print('нечётное')
else:
  print('чётное')

# задание 3
n=int(input('введите число '))
if n>40:
  print('stonks')
elif n<40:
  print('not stonks')
else:
  print('нет в условии')

# задание 4
n=int(input('Введите год '))
if n%4==0:
  print('True')
else:
  print('False')

# задание 5
n=int(input('Введите число '))
a=n%2
b=n%3
c=n%5
if a>0 and b>0 and c>0 and n!=2 and n!=3 and n!=5:
  print('true')
elif n==5 or n==3 or n==2:
  print('true')
else:
  print('false')

# задание 6
import math
a=int(input('Введите переменную '))
b=int(input('Введите переменную '))
if (a/b)>=3.6:
  s=a
  a=b
  b=s
  print("a", a)
  print("b", b)
elif a>=((-138/2)**1.3) and a<=(math.fabs((((-69)/28)**5.1)*4)):
  s=a
  a=b
  b=s
  print("a", a)
  print("b", b)
else:
  print("end")

# задание 7
a=int(input('Введите число '))
b=int(input('Введите число '))
c=int(input('Введите число '))
d=int(input('Введите число '))
e=int(input('Введите число '))
chet=0
otr=0
prom=0
if (a%2)==0:
  chet+=1
if (b%2)==0:
  chet+=1
if (c%2)==0:
  chet+=1
if (d%2)==0:
  chet+=1
if (e%2)==0:
  chet+=1
if a<0:
  otr+=1
if b<0:
  otr+=1
if c<0:
  otr+=1
if d<0:
  otr+=1
if e<0:
  otr+=1
if a==b or a==c or a==d or a==e or b==c or b==d or b==e or c==d or c==e or d==e:
  print("числа не уникальные")
else:
  print("числа уникальные")
if a>=(-256) and a<=(1024):
  prom+=1
if b>=(-256) and b<=(1024):
  prom+=1
if c>=(-256) and c<=(1024):
  prom+=1
if d>=(-256) and d<=(1024):
  prom+=1
if e>=(-256) and e<=(1024):
  prom+=1
print("Четных чисел",chet)
print("Отрицательных чисел", otr)
print("В промежутке лежит", prom)

# Задание повышенной сложности 1
a=int(input('Введите число '))
b=int(input('Введите число '))
c=int(input('Введите число '))
s=(((a)**2+(b)**3)/c+3)/4
if (s%2)==0:
  print("чётное")
else:
  print("нечётное")